### ISSUE TITLE
Push new release (v1.1.0)

### ISSUE THREAD

**Issue by mergeMarc** [daveismyname/sql-import#3]
It would be nice to have a new release with the new disable foreign key check #1 feature (v1.1.0 with semantic versioning).

I could update the license date and readme if requested.

**Comment by dcblogdev** [comment]
Ah yes, please do I will then do a release.

**Comment by mergeMarc** [comment]
Just realized that the new feature, in its current implementation, will break break backwards compatibility.
Will open a PR to fix this shortly.

**Comment by dcblogdev** [comment]
this has been merged and released now, apologies for the delay I didn't realise it was open, would be nice it GitHub had better ways of seeing open issues.
